# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5c774c88f871b360a7752a618b08f83b78b7ffbba6873260c7ebcad497064367242d1a729ae13226aefbc7e26ed980b8dac888279e01d78937c606a8a31d98e

test:
  secret_key_base: 147eb047bf4a61cf53393fe440bb8711414d72c17644753c46d551e86d819d5f6d2ffcf8b1dd9df2981613b43f2350407f875f0825a3cc35b167cd95e0bfd074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
